version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  test-and-deploy:
    jobs:
      - pytest
      - docker-build-and-push:
          requires:
            - pytest
          filters:
            branches:
              only: main
      - heroku-deploy:
        requires:
            - pytest
            - docker-build-and-push
          filters:
            branches:
              only: main


jobs:
  pytest:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pytest
          command: |
            cd oc_lettings
            pytest

  docker-build-and-push:
    environment:
      IMAGE_NAME: pablo213/oc_lettings
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            export TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t $IMAGE_NAME:$TAG .
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            export TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker push $IMAGE_NAME:$TAG

  heroku-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a python-django-starter web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a python-django-starter web
