version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  test-and-deploy:
    jobs:
      - pytest
      - docker-build-and-push:
        requires:
          pytest
        filters:
          branches:
            only: main


jobs:
  pytest:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pytest
          command: pytest
  docker-build-and-push:
    environment:
      IMAGE_NAME: pablo213/oc_lettings
      HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:$HASH
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME:$HASH
